### ISSUE TITLE
I met some problem 

### ISSUE THREAD

**Issue by StephenLee1985** [ramr/go-reaper#1]
for {
        var sig = <-notifications
        fmt.Printf(" - Received signal %v\n", sig)
        for {
            var wstatus syscall.WaitStatus

```
        /*
         *  Reap 'em, so that zombies don't accumulate.
         *  Plants vs. Zombies!!
         */
        pid, err := syscall.Wait4(-1, &wstatus, 0, nil)
        for syscall.EINTR == err {
            pid, err = syscall.Wait4(-1, &wstatus, 0, nil)
        }

        if syscall.ECHILD == err {
            break
        }

        fmt.Printf(" - Grim reaper cleanup: pid=%d, wstatus=%+v\n",
            pid, wstatus)
                  // I think  it should be break here
                 break;
    }
}
```

**Comment by ramr** [comment]
@StephenLee1985  Sorry for the delay in replying - been out of commission for a bit. 
We actually don't want to break there. The reason the inner for loop exists is because its possible that there could be more than 1 child processes that terminated whilst processing the signal and so we need to reap them all. 
The inner for loop does that waiting till there are no more `unwaited-for` children - the break is done when the error from `Wait4` is `ECHILD`.
